---
# tasks file for roles

- name: Set task variables
  set_fact:
    _subnet_id: "{{ subnet_id }}"
    _vpc_id: "{{ vpc_id }}"
    _ca_key: "{{ lookup('file', 'example-ca-key.pem') }}"
    _ca_cert: "{{ lookup('file', 'example-ca-cert.pem') }}"
    _local_cidr_ip: "{{ local_cidr_ip }}"
    _sg_name: "{{ sg_name }}"
    _key_name: "{{ key_name }}"

# - name: ensure ssh key pair named "{{ _key_name }}"
#   ec2_key:
#     name: "{{ _key_name }}"
#     key_material: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

# - name: ensure security group named "{{ _sg_name }}"
#   ec2_group:
#     name: "{{ _sg_name }}"
#     description: security group for proxy
#     vpc_id: "{{ _vpc_id }}"
#     rules:
#       - proto: all
#         cidr_ip: "{{ _local_cidr_ip }}"
#         rule_desc: allow all local

- name: start proxy instance"
  ec2_instance:
    wait: no
    name: "{{ item }}-proxy"
    key_name: "aws"
    vpc_subnet_id: "{{ _subnet_id }}"
    instance_type: "{{ proxy_instance_type }}"
    security_group: "{{ _sg_name }}"
    user_data: "{{ lookup('template', 'user_data.sh.j2') }}"
    image_id: "{{ proxy_ami }}"
    tags:
      Name: "{{ item }}-proxy"
  loop:
     - squid
    #  - mitm
    #  - nginx
    # - pound
